apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Canlı (Production) ortamı base mimariyi devralır
resources:
  - ../../base

# Canlı ortama özel Ingress, Pod Anti-Affinity, Güvenlik ve SSL Yamaları (Patches)
patches:
  - path: patches/ingress-patch.yaml
  - path: patches/app-patch.yaml
  - path: patches/phpmyadmin-patch.yaml

