apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

# Temel Kubernetes manifest kaynakları
resources:
  - apps/app.yaml
  - apps/hpa.yaml
  - apps/ingress.yaml
  - apps/phpmyadmin.yaml
  - datastores/mysql.yaml
  - datastores/redis.yaml
  - datastores/vitess.yaml
  - monitoring/servicemonitors.yaml
  - monitoring/vitess-podmonitor.yaml
  - monitoring/prometheus-rules.yaml
  - monitoring/alertmanager-config.yaml
  - monitoring/blackbox-exporter.yaml
  - monitoring/monitoring-ingress.yaml



# Otomatik Secret üreteci (Vitess VTGate Auth)
secretGenerator:
  - name: vtgate-auth
    files:
      - configs/users.json

# Otomatik ConfigMap üreteci
configMapGenerator:
  - name: nginx-config
    files:
      - configs/default.conf
  - name: cyclechain-overview-dashboard
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - monitoring/dashboards/cyclechain-overview.json
  - name: cyclechain-application-dashboard
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - monitoring/dashboards/cyclechain-application.json
  - name: cyclechain-datastores-dashboard
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - monitoring/dashboards/cyclechain-datastores.json
  - name: cyclechain-vitess-dashboard
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - monitoring/dashboards/cyclechain-vitess.json

